"""Data Export & Analysis Report — CSV download + a compiled plain-text report
that also pulls in AI outputs generated by other steps (if present)."""

import pandas as pd
import streamlit as st

from tabular.context import DatasetContext


def render(df: pd.DataFrame, ctx: DatasetContext, tabular_file=None) -> None:
    st.markdown("## Data Export & Analysis Report")
    st.caption("Export the current dataset and generate a complete analysis report.")

    if df is None or df.empty:
        st.info("Upload a dataset to enable data export.")
        return

    st.markdown("### Export Summary")
    c1, c2, c3 = st.columns(3)
    with c1:
        st.metric("Rows", f"{len(df):,}")
    with c2:
        st.metric("Columns", f"{len(df.columns):,}")
    with c3:
        st.metric("Missing Values", f"{int(df.isna().sum().sum()):,}")

    st.markdown("### Download Current Dataset")
    csv_data = df.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="Download Cleaned Dataset (CSV)",
        data=csv_data,
        file_name="cleaned_dataset.csv",
        mime="text/csv",
        key="step15_download_csv",
    )

    st.markdown("### Generate Analysis Report")

    if st.button("Generate Complete Analysis Report", key="step15_generate_report"):
        report = _build_report(df)
        st.session_state["complete_analysis_report"] = report
        st.success("Complete analysis report generated successfully.")

    if st.session_state.get("complete_analysis_report"):
        st.markdown("### Complete Analysis Report")
        st.text_area(
            "Report Preview",
            st.session_state["complete_analysis_report"],
            height=500,
            key="step15_report_preview",
        )

        report_download = st.session_state["complete_analysis_report"].encode("utf-8")
        st.download_button(
            label="Download Analysis Report",
            data=report_download,
            file_name="data_analysis_report.txt",
            mime="text/plain",
            key="step15_download_report",
        )


def _build_report(df: pd.DataFrame) -> str:
    report_rows = len(df)
    report_columns = len(df.columns)
    report_missing = int(df.isna().sum().sum())
    report_duplicates = int(df.duplicated().sum())

    report_column_details = []
    for column in df.columns:
        series = df[column]
        missing_count = int(series.isna().sum())
        unique_count = int(series.nunique(dropna=True))
        report_column_details.append(
            {
                "Column": column,
                "Data Type": str(series.dtype),
                "Missing Values": missing_count,
                "Missing %": round(missing_count / report_rows * 100, 2) if report_rows else 0,
                "Unique Values": unique_count,
            }
        )

    report_numeric_columns = df.select_dtypes(include="number").columns.tolist()
    report_numeric_details = []
    for column in report_numeric_columns:
        series = df[column].dropna()
        if series.empty:
            continue
        report_numeric_details.append(
            {
                "Column": column,
                "Mean": round(float(series.mean()), 3),
                "Median": round(float(series.median()), 3),
                "Minimum": round(float(series.min()), 3),
                "Maximum": round(float(series.max()), 3),
            }
        )

    total_cells = report_rows * report_columns
    missing_percentage = (report_missing / total_cells) * 100 if total_cells > 0 else 0
    duplicate_percentage = (report_duplicates / report_rows) * 100 if report_rows > 0 else 0
    report_constant_columns = [c for c in df.columns if df[c].nunique(dropna=False) <= 1]

    health_score = 100.0
    health_score -= min(missing_percentage, 40)
    health_score -= min(duplicate_percentage, 20)
    if report_columns > 0:
        constant_percentage = (len(report_constant_columns) / report_columns) * 100
        health_score -= min(constant_percentage, 20)
    health_score = max(0, min(100, health_score))

    lines = []
    lines.append("DATA ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append("1. DATASET SUMMARY")
    lines.append("-" * 60)
    lines.append(f"Rows: {report_rows:,}")
    lines.append(f"Columns: {report_columns:,}")
    lines.append(f"Missing Values: {report_missing:,}")
    lines.append(f"Duplicate Rows: {report_duplicates:,}")
    lines.append(f"Dataset Health Score: {health_score:.1f}/100")
    lines.append("")

    lines.append("2. COLUMN PROFILE")
    lines.append("-" * 60)
    for detail in report_column_details:
        lines.append(f"Column: {detail['Column']}")
        lines.append(f"  Data Type: {detail['Data Type']}")
        lines.append(f"  Missing Values: {detail['Missing Values']}")
        lines.append(f"  Missing %: {detail['Missing %']:.2f}%")
        lines.append(f"  Unique Values: {detail['Unique Values']}")
        lines.append("")

    lines.append("3. NUMERIC COLUMN ANALYSIS")
    lines.append("-" * 60)
    if report_numeric_details:
        for detail in report_numeric_details:
            lines.append(f"Column: {detail['Column']}")
            lines.append(f"  Mean: {detail['Mean']}")
            lines.append(f"  Median: {detail['Median']}")
            lines.append(f"  Minimum: {detail['Minimum']}")
            lines.append(f"  Maximum: {detail['Maximum']}")
            lines.append("")
    else:
        lines.append("No numeric columns available.")

    lines.append("4. DATA QUALITY FINDINGS")
    lines.append("-" * 60)
    lines.append(
        f"Missing values detected: {report_missing:,} ({missing_percentage:.2f}%)."
        if report_missing > 0 else "No missing values detected."
    )
    lines.append(
        f"Duplicate rows detected: {report_duplicates:,}."
        if report_duplicates > 0 else "No duplicate rows detected."
    )
    if report_constant_columns:
        lines.append("Constant columns:")
        for column in report_constant_columns:
            lines.append(f"  - {column}")
    else:
        lines.append("No constant columns detected.")
    lines.append("")

    lines.append("5. CLEANING / TRANSFORMATION HISTORY")
    lines.append("-" * 60)
    cleaning_history_found = False

    if "step10_last_cleaning" in st.session_state:
        cleaning_history_found = True
        step10_cleaning = st.session_state["step10_last_cleaning"]
        lines.append("Step 10:")
        lines.append(f"  Operation: {step10_cleaning.get('operation', 'N/A')}")

    if "step13_last_cleaning" in st.session_state:
        cleaning_history_found = True
        step13_cleaning = st.session_state["step13_last_cleaning"]
        lines.append("Step 13:")
        lines.append(f"  Operation: {step13_cleaning.get('operation', 'N/A')}")
        lines.append(
            f"  Rows: {step13_cleaning.get('rows_before', 0):,} → "
            f"{step13_cleaning.get('rows_after', 0):,}"
        )
        lines.append(
            f"  Columns: {step13_cleaning.get('columns_before', 0):,} → "
            f"{step13_cleaning.get('columns_after', 0):,}"
        )

    if not cleaning_history_found:
        lines.append("No cleaning operations recorded.")
    lines.append("")

    lines.append("6. AI DATA QUALITY REPORT")
    lines.append("-" * 60)
    lines.append(
        str(st.session_state["ai_quality_report"])
        if "ai_quality_report" in st.session_state
        else "AI quality report has not been generated."
    )
    lines.append("")

    lines.append("7. AI CLEANING RECOMMENDATIONS")
    lines.append("-" * 60)
    lines.append(
        str(st.session_state["ai_cleaning_plan"])
        if "ai_cleaning_plan" in st.session_state
        else "AI cleaning plan has not been generated."
    )
    lines.append("")

    lines.append("=" * 60)
    lines.append("END OF REPORT")

    return "\n".join(lines)
